---
abstract: 'Simple random password generator'
author:
  - 'Ryo Okamoto <ryo@aquahill.net>'
build_requires:
  List::MoreUtils: 0
  Test::More: 0.88
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SimplePassword
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Data::SimplePassword:
    file: lib/Data/SimplePassword.pm
    version: 0.08
recommends:
  Math::Random::MT: 0
requires:
  CLASS: 0
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  Crypt::Random: 0
  Math::Random::MT::Perl: 0
  UNIVERSAL::require: 0
  perl: 5.00502
resources:
  bugtracker: https://github.com/ryochin/p5-data-simplepassword/issues
  homepage: https://github.com/ryochin/p5-data-simplepassword
  repository: git://github.com/ryochin/p5-data-simplepassword.git
version: 0.08
